version: '3'
services:
  db:
    image: postgres:11.5-alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/bash -c "bundle exec rails s -b 0.0.0.0 -p 3000"
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./:/var/www
