version: '3'
services:
  db:
    image: postgres:11.5-alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/var/www/app
    depends_on:
      - db
