version: '3'
services:
  app:
    tty: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash ./deployment_scripts/deploy.sh
    volumes:
      - .:/var/www/app
    ports:
      - "80:3000"
